controller_list:
  - name: j2n6s300_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - robot_j2n6s300_joint_1
      - robot_j2n6s300_joint_2
      - robot_j2n6s300_joint_3
      - robot_j2n6s300_joint_4
      - robot_j2n6s300_joint_5
      - robot_j2n6s300_joint_6
  - name: j2n6s300_gripper_controller
    action_ns: gripper_command
    type: GripperCommand
    default: True
    joints:
      - robot_j2n6s300_joint_finger_1
      - robot_j2n6s300_joint_finger_2
      - robot_j2n6s300_joint_finger_3