obstacle_range: 3
raytrace_range: 5
footprint: [[-0.35, -0.3], [-0.35, 0.3], [0.35, 0.3], [0.35, -0.3]]
footprint_padding: 0.05

obstacle_layer: 
  observation_sources: laser_scan
  laser_scan: {
    sensor_frame: camera_front_link,
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true
  }


inflation_layer:
  inflation_radius: 0.55
